/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

public class AdminUsuarioCRUDWindow extends javax.swing.JFrame {

    public javax.swing.JButton getRegresarBtn() {
        return regresarBtn;
    }

    public void setRegresarBtn(javax.swing.JButton regresarBtn) {
        this.regresarBtn = regresarBtn;
    }

    public javax.swing.JButton getAniadirAdminBtn() {
        return aniadirAdminBtn;
    }

    public void setAniadirAdminBtn(javax.swing.JButton aniadirAdminBtn) {
        this.aniadirAdminBtn = aniadirAdminBtn;
    }

    public javax.swing.JButton getAniadirUsuarioBtn() {
        return aniadirUsuarioBtn;
    }

    public void setAniadirUsuarioBtn(javax.swing.JButton aniadirUsuarioBtn) {
        this.aniadirUsuarioBtn = aniadirUsuarioBtn;
    }

    public javax.swing.JButton getBuscarUsuarioBtn() {
        return buscarUsuarioBtn;
    }

    public void setBuscarUsuarioBtn(javax.swing.JButton buscarUsuarioBtn) {
        this.buscarUsuarioBtn = buscarUsuarioBtn;
    }

    public javax.swing.JButton getEliminarUsuarioBtn() {
        return eliminarUsuarioBtn;
    }

    public void setEliminarUsuarioBtn(javax.swing.JButton eliminarUsuarioBtn) {
        this.eliminarUsuarioBtn = eliminarUsuarioBtn;
    }

    public javax.swing.JButton getModificarUsuarioBtn() {
        return modificarUsuarioBtn;
    }

    public void setModificarUsuarioBtn(javax.swing.JButton modificarUsuarioBtn) {
        this.modificarUsuarioBtn = modificarUsuarioBtn;
    }

    public javax.swing.JTextField getjTextField1() {
        return jTextField1;
    }

    public void setjTextField1(javax.swing.JTextField jTextField1) {
        this.jTextField1 = jTextField1;
    }

    public javax.swing.JTextField getjTextField4() {
        return jTextField4;
    }

    public void setjTextField4(javax.swing.JTextField jTextField4) {
        this.jTextField4 = jTextField4;
    }

    public javax.swing.JTextField getNombreTxtField() {
        return nombreTxtField;
    }

    public void setNombreTxtField(javax.swing.JTextField nombreTxtField) {
        this.nombreTxtField = nombreTxtField;
    }
   
    public javax.swing.JTextField getUsuarioTxtField() {
        return usuarioTxtField;
    }

    public void setUsuarioTxtField(javax.swing.JTextField usuarioTxtField) {
        this.usuarioTxtField = usuarioTxtField;
    }

    public javax.swing.JButton getAniadirUsuario() {
        return getAniadirUsuarioBtn();
    }

    public void setAniadirUsuario(javax.swing.JButton aniadirUsuario) {
        this.setAniadirUsuarioBtn(aniadirUsuario);
    }

    public javax.swing.JTextField getApellidoTxtField() {
        return apellidoTxtField;
    }

    public void setApellidoTxtField(javax.swing.JTextField apellidoTxtField) {
        this.apellidoTxtField = apellidoTxtField;
    }

    public javax.swing.JPasswordField getConfirmeContraseniaTxtField() {
        return confirmeContraseniaTxtField;
    }

    public void setConfirmeContraseniaTxtField(javax.swing.JPasswordField confirmeContraseniaTxtField) {
        this.confirmeContraseniaTxtField = confirmeContraseniaTxtField;
    }

    public javax.swing.JTextField getCurpTxtField() {
        return curpTxtField;
    }

    public void setCurpTxtField(javax.swing.JTextField curpTxtField) {
        this.curpTxtField = curpTxtField;
    }

    public javax.swing.JPasswordField getIngreseContraseniaTxtField() {
        return ingreseContraseniaTxtField;
    }

    public void setIngreseContraseniaTxtField(javax.swing.JPasswordField ingreseContraseniaTxtField) {
        this.ingreseContraseniaTxtField = ingreseContraseniaTxtField;
    }

    /**
     * Creates new form AdminMainWindow
     */
    public AdminUsuarioCRUDWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        regresarBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        aniadirUsuarioBtn = new javax.swing.JButton();
        nombreTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        apellidoTxtField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        curpTxtField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        usuarioTxtField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ingreseContraseniaTxtField = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        confirmeContraseniaTxtField = new javax.swing.JPasswordField();
        modificarUsuarioBtn = new javax.swing.JButton();
        buscarUsuarioBtn = new javax.swing.JButton();
        eliminarUsuarioBtn = new javax.swing.JButton();
        aniadirAdminBtn = new javax.swing.JButton();

        jButton3.setText("Añadir Usuario");

        jButton4.setText("Modificar Usuario");

        jButton5.setText("Modificar Cartelera");

        jButton6.setText("Regresar");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMINISTRADOR");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jButton1.setText("Añadir Obras");

        jButton2.setText("Modificar Obras");

        jTextField1.setText("jTextField1");

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Apellido");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 30, 46));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 300));

        regresarBtn.setBackground(new java.awt.Color(88, 91, 112));
        regresarBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        regresarBtn.setForeground(new java.awt.Color(255, 255, 255));
        regresarBtn.setText("Regresar");
        regresarBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        regresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(205, 214, 244));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADMINISTRADOR");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario");

        aniadirUsuarioBtn.setBackground(new java.awt.Color(88, 91, 112));
        aniadirUsuarioBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        aniadirUsuarioBtn.setForeground(new java.awt.Color(255, 255, 255));
        aniadirUsuarioBtn.setText("Añadir");
        aniadirUsuarioBtn.setToolTipText("");
        aniadirUsuarioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aniadirUsuarioBtnActionPerformed(evt);
            }
        });

        nombreTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTxtFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre");

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Apellido");

        apellidoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoTxtFieldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CURP");

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Usuario");

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ingrese contraseña");

        ingreseContraseniaTxtField.setText("jPasswordField1");

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Confirme contraseña");

        confirmeContraseniaTxtField.setText("jPasswordField1");

        modificarUsuarioBtn.setBackground(new java.awt.Color(88, 91, 112));
        modificarUsuarioBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        modificarUsuarioBtn.setForeground(new java.awt.Color(255, 255, 255));
        modificarUsuarioBtn.setText("Modificar");
        modificarUsuarioBtn.setToolTipText("");
        modificarUsuarioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarUsuarioBtnActionPerformed(evt);
            }
        });

        buscarUsuarioBtn.setBackground(new java.awt.Color(88, 91, 112));
        buscarUsuarioBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        buscarUsuarioBtn.setForeground(new java.awt.Color(255, 255, 255));
        buscarUsuarioBtn.setText("Buscar");
        buscarUsuarioBtn.setToolTipText("");
        buscarUsuarioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarUsuarioBtnActionPerformed(evt);
            }
        });

        eliminarUsuarioBtn.setBackground(new java.awt.Color(88, 91, 112));
        eliminarUsuarioBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        eliminarUsuarioBtn.setForeground(new java.awt.Color(255, 255, 255));
        eliminarUsuarioBtn.setText("Eliminar");
        eliminarUsuarioBtn.setToolTipText("");
        eliminarUsuarioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarUsuarioBtnActionPerformed(evt);
            }
        });

        aniadirAdminBtn.setBackground(new java.awt.Color(88, 91, 112));
        aniadirAdminBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        aniadirAdminBtn.setForeground(new java.awt.Color(255, 255, 255));
        aniadirAdminBtn.setText("Añadir como administrador");
        aniadirAdminBtn.setToolTipText("");
        aniadirAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aniadirAdminBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(curpTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(regresarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(apellidoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usuarioTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(confirmeContraseniaTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ingreseContraseniaTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(aniadirUsuarioBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modificarUsuarioBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarUsuarioBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminarUsuarioBtn)))
                .addGap(123, 123, 123))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(aniadirAdminBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(regresarBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nombreTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(curpTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(apellidoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(usuarioTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ingreseContraseniaTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(confirmeContraseniaTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aniadirUsuarioBtn)
                    .addComponent(modificarUsuarioBtn)
                    .addComponent(buscarUsuarioBtn)
                    .addComponent(eliminarUsuarioBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aniadirAdminBtn)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regresarBtnActionPerformed

    private void aniadirUsuarioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aniadirUsuarioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aniadirUsuarioBtnActionPerformed

    private void nombreTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTxtFieldActionPerformed

    private void apellidoTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoTxtFieldActionPerformed

    private void modificarUsuarioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarUsuarioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarUsuarioBtnActionPerformed

    private void buscarUsuarioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarUsuarioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarUsuarioBtnActionPerformed

    private void eliminarUsuarioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarUsuarioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarUsuarioBtnActionPerformed

    private void aniadirAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aniadirAdminBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aniadirAdminBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUsuarioCRUDWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton aniadirAdminBtn;
    public javax.swing.JButton aniadirUsuarioBtn;
    public javax.swing.JTextField apellidoTxtField;
    public javax.swing.JButton buscarUsuarioBtn;
    public javax.swing.JPasswordField confirmeContraseniaTxtField;
    public javax.swing.JTextField curpTxtField;
    public javax.swing.JButton eliminarUsuarioBtn;
    public javax.swing.JPasswordField ingreseContraseniaTxtField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    public javax.swing.JButton modificarUsuarioBtn;
    public javax.swing.JTextField nombreTxtField;
    public javax.swing.JButton regresarBtn;
    public javax.swing.JTextField usuarioTxtField;
    // End of variables declaration//GEN-END:variables
}
